### ISSUE TITLE
Fixed height is not working. 

### ISSUE THREAD

**Issue by anisulislampranto** [dkaoster/scrolly-video#72] opened 2023-11-22 07:20 UTC
I want to set a fixed height for the video and it's not working. and it is behaving wired. 

<img width="427" alt="Screenshot 2023-11-23 at 8 56 11 PM" src="https://github.com/dkaoster/scrolly-video/assets/76773444/4d182c88-2bbb-4dd7-91ea-248bfac1734d">

Uploading Screen Recording 2023-11-23 at 8.59.49 PM.mp4…

**Comment by dkaoster** [comment] 2023-11-23 16:22
Hi, are you able to provide more details such as a github repo where I can see the issue? This is a little bit difficult to know what the issue is.

**Comment by anisulislampranto** [comment] 2023-11-26 06:25
> Hi, are you able to provide more details such as a github repo where I can see the issue? This is a little bit difficult to know what the issue is.

https://github.com/anisulislampranto/onscroll-video-play
this is a dummy repo i can't show you the real repo because it is private. but code is same. anyway. now from this code i want to give a fixed height. how can i do it ?

**Comment by dkaoster** [comment] 2023-11-26 07:02
Hi @anisulislampranto,

For the dummy repo you sent me, I was able to set a fixed height by adding:

```
<style>
{`.mt-20 video {
height: 400px !important;
min-height: unset !important;
}`}
</style>
```

Yes, this is a little bit hacky and not the best way to do it, but for now there is no easy way to customize the style of the video beyond what is written in the documentation. I'll keep this in mind for future versions, and am also happy to review a PR if you'd like to build out this feature.

**Comment by anisulislampranto** [comment] 2023-11-26 07:46
> Hi @anisulislampranto,
> 
> For the dummy repo you sent me, I was able to set a fixed height by adding:
> 
> ```
> <style>
> {`.mt-20 video {
> height: 400px !important;
> min-height: unset !important;
> }`}
> </style>
> ```
> 
> Yes, this is a little bit hacky and not the best way to do it, but for now there is no easy way to customize the style of the video beyond what is written in the documentation. I'll keep this in mind for future versions, and am also happy to review a PR if you'd like to build out this feature.

it is not working somehow. could you have a look at the code i've pushed.

**Comment by dkaoster** [comment] 2023-11-26 18:56
![Screenshot 2023-11-26 at 11 54 41 AM](https://github.com/dkaoster/scrolly-video/assets/3477162/43b92a2b-0905-472f-8ec5-f4fa370c92ae)

works perfectly for me in both firefox and chrome, the height is now fixed to 400px as set in the css.

**Closed** 2024-01-07 23:27 UTC
